### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by jfmartinz**
This pull request added new PR template file(md). To guide and help contributors in providing details about their pull requests.

Enhancements to pull request template:

* [`.github/pull_request_template.md`](diffhunk://#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bR1-R21): Added sections for description, type of change, checklist, and additional information to ensure contributors provide thorough and consistent details.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Hi @tthvo, here is the template. If you have more suggestions to add or maybe improve in this template, then let me know. Thanks

**Review by tthvo — APPROVED** [review]
> Hi @tthvo, here is the template. If you have more suggestions to add or maybe improve in this template, then let me know. Thanks

Hey @jfmartinz, this looks good! Thanks for your contributions!

**Comment by jfmartinz** [comment]
Btw, there is a typo in the tag:

image

**Comment by tthvo** [comment]
> Btw, there is a typo in the tag:
> 
> image

Fixed, thanks!

**Pull request merged**
